// Generated by CoffeeScript 1.4.0

/*
 *
 *  jQuery Bounce by Gary Hepting - https://github.com/ghepting/jquery-bounce
 *  
 *  Open source under the BSD License.
 *
 *  Copyright © 2013 Gary Hepting. All rights reserved.
 *
*/


(function() {

  (function($) {
    return $.fn.bounce = function(options) {
      var defaults, interval, timeout;
      defaults = {
        id: $(this).attr("id"),
        distance: "20px",
        downspeed: 250,
        upspeed: 350,
        gravity: "bottom",
        timer: 600,
        delay: 0,
        loop: 0,
        easingdown: "easeInQuad",
        easingup: "jswing"
      };
      if (defaults.timer < defaults.downspeed + defaults.upspeed) {
        defaults.timer = defaults.downspeed + defaults.upspeed;
      }
      options = $.extend(defaults, options);
      interval = [];
      timeout = [];
      return this.each(function(obj) {
        obj = $(this);
        obj.wrap('<div style="display:inline-block;position:relative;width:' + obj.outerWidth() + 'px;height:' + (obj.outerHeight() + parseInt(options.distance)) + 'px;" />');
        obj.css("position", "absolute");
        setTimeout(function() {
          obj.stop().animate({
            "margin-top": (options.gravity === "top" ? "-" : "") + options.distance,
            opacity: "1"
          }, options.downspeed, options.easingdown).animate({
            "margin-top": "0",
            opacity: "1"
          }, options.upspeed, options.easingup);
          return obj.interval = setInterval(function() {
            return obj.stop().animate({
              "margin-top": (options.gravity === "top" ? "-" : "") + options.distance,
              opacity: "1"
            }, options.downspeed, options.easingdown).animate({
              "margin-top": "0",
              opacity: "1"
            }, options.upspeed, options.easingup);
          }, options.timer);
        }, options.delay);
        if (options.loop > 0) {
          return obj.timeout = setTimeout(function() {
            return clearInterval(obj.interval);
          }, (options.loop + 1) * options.timer);
        }
      });
    };
  })(jQuery);

}).call(this);
